apiVersion: v1
data:
  VAULT_KEY: ODNiZWEyYWUtMzU2Ny05ODIwLWFjZWQtYmJkOWEwZTY4MWI5
kind: Secret
metadata:
  creationTimestamp: "2024-01-11T07:59:51Z"
  name: vault-springboot-secrate
  namespace: default
  resourceVersion: "17264"
  uid: 6501b07a-3db1-4096-8547-0a81add86e41
type: Opaque