---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: otlp-k8s-spring-app
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: otlp-k8s-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otlp-k8s-spring-app
      app.kubernetes.io/version: 0.0.1-SNAPSHOT
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: 'true'
      labels:
        app.kubernetes.io/name: otlp-k8s-spring-app
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: ghcr.io/nikhil12894/otlp-k8s-spring-app
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: otlp-k8s-spring-app
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
      imagePullSecrets:
        - name: dockerconfigjson-github-com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: otlp-k8s-spring-app
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: otlp-k8s-spring-app
spec:
  rules:
    - host: ""
      http:
        paths:
          - backend:
              service:
                name: otlp-k8s-spring-app
                port:
                  name: http
            path: /
            pathType: Prefix
          - backend:
              service:
                name: otlp-k8s-spring-app
                port:
                  name: http
            path: /hello
            pathType: Prefix
          - backend:
              service:
                name: otlp-k8s-spring-app
                port:
                  name: http
            path: /errot
            pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: otlp-k8s-spring-app
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: otlp-k8s-spring-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: otlp-k8s-spring-app
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  type: ClusterIP
